operationId: kubernetes_get_credentials

summary: Retrieve Credentials for a Kubernetes Cluster

description: |
  This endpoint returns a JSON object . It can be used to programmatically
  construct Kubernetes clients which cannot parse kubeconfig files.

  The resulting JSON object contains token-based authentication for clusters
  supporting it, and certificate-based authentication otherwise. For a list of
  supported versions and more information, see "[How to Connect to a DigitalOcean
  Kubernetes Cluster with kubectl](https://www.digitalocean.com/docs/kubernetes/how-to/connect-with-kubectl/)".

  To retrieve credentials for accessing a Kubernetes cluster, send a GET
  request to `/v2/kubernetes/clusters/$K8S_CLUSTER_ID/credentials`.

  Clusters supporting token-based authentication may define an expiration by
  passing a duration in seconds as a query parameter to
  `/v2/kubernetes/clusters/$K8S_CLUSTER_ID/credentials?expiry_seconds=$DURATION_IN_SECONDS`.
  If not set or 0, then the token will have a 7 day expiry. The query parameter
  has no impact in certificate-based authentication.

tags:
  - Kubernetes

parameters:
  - $ref: 'parameters.yml#/kubernetes_cluster_id'
  - $ref: 'parameters.yml#/kubernetes_expiry_seconds'

responses:
  '200':
    $ref: 'responses/credentials.yml'

  '401':
    $ref: '../../shared/responses/unauthorized.yml'

  '404':
    $ref: '../../shared/responses/not_found.yml'

  '429':
    $ref: '../../shared/responses/too_many_requests.yml'

  '500':
    $ref: '../../shared/responses/server_error.yml'

  default:
    $ref: '../../shared/responses/unexpected_error.yml'

x-codeSamples:
  - $ref: 'examples/curl/kubernetes_get_credentials.yml'
  - $ref: 'examples/go/kubernetes_get_credentials.yml'
  - $ref: 'examples/ruby/kubernetes_get_credentials.yml'
  - $ref: 'examples/python/kubernetes_get_credentials.yml'

security:
  - bearer_auth:
    - 'kubernetes:access_cluster'
