operationId: kubernetes_upgrade_cluster

summary: Upgrade a Kubernetes Cluster

description: |
  To immediately upgrade a Kubernetes cluster to a newer patch release of
  Kubernetes, send a POST request to `/v2/kubernetes/clusters/$K8S_CLUSTER_ID/upgrade`.
  The body of the request must specify a version attribute.

  Available upgrade versions for a cluster can be fetched from
  `/v2/kubernetes/clusters/$K8S_CLUSTER_ID/upgrades`.

tags:
  - Kubernetes

parameters:
  - $ref: 'parameters.yml#/kubernetes_cluster_id'

requestBody:
  required: true

  content:
    application/json:
      schema:
        properties:
          version:
            type: string
            example: 1.16.13-do.0
            description: The slug identifier for the version of Kubernetes that
              the cluster will be upgraded to.

responses:
  '202':
    $ref: '../../shared/responses/accepted.yml'

  '401':
    $ref: '../../shared/responses/unauthorized.yml'

  '404':
    $ref: '../../shared/responses/not_found.yml'

  '429':
    $ref: '../../shared/responses/too_many_requests.yml'

  '500':
    $ref: '../../shared/responses/server_error.yml'

  default:
    $ref: '../../shared/responses/unexpected_error.yml'

x-codeSamples:
  - $ref: 'examples/curl/kubernetes_upgrade_cluster.yml'
  - $ref: 'examples/go/kubernetes_upgrade_cluster.yml'
  - $ref: 'examples/python/kubernetes_upgrade_cluster.yml'

security:
  - bearer_auth:
    - 'kubernetes:update'
