operationId: kubernetes_destroy_associatedResourcesDangerous

summary: Delete a Cluster and All of its Associated Resources (Dangerous)

description: |
  To delete a Kubernetes cluster with all of its associated resources, send a
  DELETE request to `/v2/kubernetes/clusters/$K8S_CLUSTER_ID/destroy_with_associated_resources/dangerous`.
  A 204 status code with no body will be returned in response to a successful request.

tags:
  - Kubernetes

parameters:
  - $ref: 'parameters.yml#/kubernetes_cluster_id'

responses:
  '204':
    $ref: '../../shared/responses/no_content.yml'

  '401':
    $ref: '../../shared/responses/unauthorized.yml'

  '404':
    $ref: '../../shared/responses/not_found.yml'

  '429':
    $ref: '../../shared/responses/too_many_requests.yml'

  '500':
    $ref: '../../shared/responses/server_error.yml'

  default:
    $ref: '../../shared/responses/unexpected_error.yml'

x-codeSamples:
  - $ref: 'examples/curl/kubernetes_destroy_associatedResourcesDangerous.yml'
  - $ref: 'examples/go/kubernetes_destroy_associatedResourcesDangerous.yml'
  - $ref: 'examples/python/kubernetes_destroy_associatedResourcesDangerous.yml'

security:
  - bearer_auth:
    - 'kubernetes:delete'
