operationId: kubernetes_add_nodePool

summary: Add a Node Pool to a Kubernetes Cluster

description: |
  To add an additional node pool to a Kubernetes clusters, send a POST request
  to `/v2/kubernetes/clusters/$K8S_CLUSTER_ID/node_pools` with the following
  attributes.

tags:
  - Kubernetes

parameters:
  - $ref: 'parameters.yml#/kubernetes_cluster_id'

requestBody:
  required: true

  content:
    application/json:
      schema:
        $ref: 'models/node_pool.yml#/kubernetes_node_pool'

      example:
        size: s-1vcpu-2gb
        count: 3
        name: new-pool
        tags:
        - frontend
        auto_scale: true
        min_nodes: 3
        max_nodes: 6

responses:
  '201':
    $ref: 'responses/node_pool_create.yml'

  '401':
    $ref: '../../shared/responses/unauthorized.yml'

  '404':
    $ref: '../../shared/responses/not_found.yml'

  '429':
    $ref: '../../shared/responses/too_many_requests.yml'

  '500':
    $ref: '../../shared/responses/server_error.yml'

  default:
    $ref: '../../shared/responses/unexpected_error.yml'

x-codeSamples:
  - $ref: 'examples/curl/kubernetes_add_nodePool.yml'
  - $ref: 'examples/go/kubernetes_add_nodePool.yml'
  - $ref: 'examples/ruby/kubernetes_add_nodePool.yml'
  - $ref: 'examples/python/kubernetes_add_nodePool.yml'

security:
  - bearer_auth:
    - 'kubernetes:create'
