operationId: kubernetes_create_cluster

summary: Create a New Kubernetes Cluster

description: |
  To create a new Kubernetes cluster, send a POST request to
  `/v2/kubernetes/clusters`. The request must contain at least one node pool
  with at least one worker.

  The request may contain a maintenance window policy describing a time period
  when disruptive maintenance tasks may be carried out. Omitting the policy
  implies that a window will be chosen automatically. See
  [here](https://www.digitalocean.com/docs/kubernetes/how-to/upgrade-cluster/)
  for details.

tags:
  - Kubernetes

requestBody:
  required: true

  content:
    application/json:
      schema:
        $ref: 'models/cluster.yml'

      examples:
        Kubernetes Cluster Request:
          $ref: 'examples.yml#/kubernetes_clusters_basic_request'
        Kubernetes Cluster with Multiple Node Pools Request:
          $ref: 'examples.yml#/kubernetes_clusters_multi_pool_request'

responses:
  '201':
    $ref: 'responses/cluster_create.yml'

  '401':
    $ref: '../../shared/responses/unauthorized.yml'

  '429':
    $ref: '../../shared/responses/too_many_requests.yml'

  '500':
    $ref: '../../shared/responses/server_error.yml'

  default:
    $ref: '../../shared/responses/unexpected_error.yml'

x-codeSamples:
  - $ref: 'examples/curl/kubernetes_create_cluster.yml'
  - $ref: 'examples/go/kubernetes_create_cluster.yml'
  - $ref: 'examples/ruby/kubernetes_create_cluster.yml'
  - $ref: 'examples/python/kubernetes_create_cluster.yml'

security:
  - bearer_auth:
    - 'kubernetes:create'
