operationId: apps_create_deployment

summary: Create an App Deployment

description: Creating an app deployment will pull the latest changes from your repository
  and schedule a new deployment for your app.

tags:
- Apps

parameters:
  - $ref: parameters.yml#/app_id

requestBody:
  content:
    application/json:
      schema:
        $ref: models/apps_create_deployment_request.yml
  required: true

responses:
  "200":
    $ref: responses/new_app_deployment.yml

  "401":
    $ref: ../../shared/responses/unauthorized.yml

  '404':
    $ref: '../../shared/responses/not_found.yml'

  "429":
    $ref: "../../shared/responses/too_many_requests.yml"

  "500":
    $ref: ../../shared/responses/server_error.yml

  default:
    $ref: ../../shared/responses/unexpected_error.yml

x-codeSamples:
  - $ref: 'examples/curl/apps_create_deployment.yml'
  - $ref: 'examples/python/apps_create_deployment.yml'

security:
  - bearer_auth:
    - 'app:create'
