description: |
  The response will be a JSON object with a key called `kubernetes_clusters`.
  This will be set to an array of objects, each of which will contain the
  standard Kubernetes cluster attributes.

headers:
  ratelimit-limit:
    $ref: '../../../shared/headers.yml#/ratelimit-limit'
  ratelimit-remaining:
    $ref: '../../../shared/headers.yml#/ratelimit-remaining'
  ratelimit-reset:
    $ref: '../../../shared/headers.yml#/ratelimit-reset'

content:
  application/json:
    schema:
      allOf:
        - type: object
          properties:
            kubernetes_clusters:
              type: array
              items:
                $ref: '../models/cluster.yml'
        - $ref: '../../../shared/pages.yml#/pagination'
        - $ref: '../../../shared/meta.yml'

    examples:
      All Kubernetes Clusters:
        $ref: 'examples.yml#/kubernetes_clusters_all'