description: A JSON object containing credentials for a cluster.

headers:
  ratelimit-limit:
    $ref: '../../../shared/headers.yml#/ratelimit-limit'
  ratelimit-remaining:
    $ref: '../../../shared/headers.yml#/ratelimit-remaining'
  ratelimit-reset:
    $ref: '../../../shared/headers.yml#/ratelimit-reset'

content:
  application/json:
    schema:
      $ref: "../models/credentials.yml"
