kubernetes_clusters_all:
  value:
    kubernetes_clusters:
    - id: bd5f5959-5e1e-4205-a714-a914373942af
      name: prod-cluster-01
      region: nyc1
      version: 1.18.6-do.0
      cluster_subnet: 10.244.0.0/16
      service_subnet: 10.245.0.0/16
      vpc_uuid: c33931f2-a26a-4e61-b85c-4e95a2ec431b
      ipv4: 68.183.121.157
      endpoint: https://bd5f5959-5e1e-4205-a714-a914373942af.k8s.ondigitalocean.com
      tags:
      - production
      - web-team
      - k8s
      - k8s:bd5f5959-5e1e-4205-a714-a914373942af
      node_pools:
      - id: cdda885e-7663-40c8-bc74-3a036c66545d
        name: frontend-pool
        size: s-1vcpu-2gb
        count: 3
        tags:
        - production
        - web-team
        - k8s
        - k8s:bd5f5959-5e1e-4205-a714-a914373942af
        - k8s:worker
        labels: null
        taints: []
        auto_scale: false
        min_nodes: 0
        max_nodes: 0
        nodes:
        - id: 478247f8-b1bb-4f7a-8db9-2a5f8d4b8f8f
          name: adoring-newton-3niq
          status:
            state: provisioning
          droplet_id: '205545370'
          created_at: '2018-11-15T16:00:11Z'
          updated_at: '2018-11-15T16:00:11Z'
        - id: ad12e744-c2a9-473d-8aa9-be5680500eb1
          name: adoring-newton-3nim
          status:
            state: provisioning
          droplet_id: '205545371'
          created_at: '2018-11-15T16:00:11Z'
          updated_at: '2018-11-15T16:00:11Z'
        - id: e46e8d07-f58f-4ff1-9737-97246364400e
          name: adoring-newton-3ni7
          status:
            state: provisioning
          droplet_id: '205545372'
          created_at: '2018-11-15T16:00:11Z'
          updated_at: '2018-11-15T16:00:11Z'
      - id: f49f4379-7e7f-4af5-aeb6-0354bd840778
        name: backend-pool
        size: g-4vcpu-16gb
        count: 2
        tags:
        - production
        - web-team
        - k8s
        - k8s:bd5f5959-5e1e-4205-a714-a914373942af
        - k8s:worker
        labels:
          service: backend
          priority: high
        taints: []
        auto_scale: true
        min_nodes: 2
        max_nodes: 5
        nodes:
        - id: 3385619f-8ec3-42ba-bb23-8d21b8ba7518
          name: affectionate-nightingale-3nif
          status:
            state: provisioning
          droplet_id: '205545373'
          created_at: '2018-11-15T16:00:11Z'
          updated_at: '2018-11-15T16:00:11Z'
        - id: 4b8f60ff-ba06-4523-a6a4-b8148244c7e6
          name: affectionate-nightingale-3niy
          status:
            state: provisioning
          droplet_id: '205545374'
          created_at: '2018-11-15T16:00:11Z'
          updated_at: '2018-11-15T16:00:11Z'
      maintenance_policy:
        start_time: '00:00'
        duration: 4h0m0s
        day: any
      auto_upgrade: false
      status:
        state: provisioning
        message: provisioning
      created_at: '2018-11-15T16:00:11Z'
      updated_at: '2018-11-15T16:00:11Z'
      surge_upgrade: false
      registry_enabled: false
      ha: false
    meta:
      total: 1

kubernetes_single:
  value:
    kubernetes_cluster:
      id: bd5f5959-5e1e-4205-a714-a914373942af
      name: prod-cluster-01
      region: nyc1
      version: 1.18.6-do.0
      cluster_subnet: 10.244.0.0/16
      service_subnet: 10.245.0.0/16
      vpc_uuid: c33931f2-a26a-4e61-b85c-4e95a2ec431b
      ipv4: 68.183.121.157
      endpoint: https://bd5f5959-5e1e-4205-a714-a914373942af.k8s.ondigitalocean.com
      tags:
      - production
      - web-team
      - k8s
      - k8s:bd5f5959-5e1e-4205-a714-a914373942af
      node_pools:
      - id: cdda885e-7663-40c8-bc74-3a036c66545d
        name: frontend-pool
        size: s-1vcpu-2gb
        count: 3
        tags:
        - production
        - web-team
        - k8s
        - k8s:bd5f5959-5e1e-4205-a714-a914373942af
        - k8s:worker
        labels: null
        taints: []
        auto_scale: false
        min_nodes: 0
        max_nodes: 0
        nodes:
        - id: 478247f8-b1bb-4f7a-8db9-2a5f8d4b8f8f
          name: adoring-newton-3niq
          status:
            state: running
          droplet_id: '205545370'
          created_at: '2018-11-15T16:00:11Z'
          updated_at: '2018-11-15T16:00:11Z'
        - id: ad12e744-c2a9-473d-8aa9-be5680500eb1
          name: adoring-newton-3nim
          status:
            state: running
          droplet_id: '205545371'
          created_at: '2018-11-15T16:00:11Z'
          updated_at: '2018-11-15T16:00:11Z'
        - id: e46e8d07-f58f-4ff1-9737-97246364400e
          name: adoring-newton-3ni7
          status:
            state: running
          droplet_id: '205545372'
          created_at: '2018-11-15T16:00:11Z'
          updated_at: '2018-11-15T16:00:11Z'
      - id: f49f4379-7e7f-4af5-aeb6-0354bd840778
        name: backend-pool
        size: g-4vcpu-16gb
        count: 2
        tags:
        - production
        - web-team
        - k8s
        - k8s:bd5f5959-5e1e-4205-a714-a914373942af
        - k8s:worker
        labels:
          service: backend
          priority: high
        taints: []
        auto_scale: true
        min_nodes: 2
        max_nodes: 5
        nodes:
        - id: 3385619f-8ec3-42ba-bb23-8d21b8ba7518
          name: affectionate-nightingale-3nif
          status:
            state: running
          droplet_id: '205545373'
          created_at: '2018-11-15T16:00:11Z'
          updated_at: '2018-11-15T16:00:11Z'
        - id: 4b8f60ff-ba06-4523-a6a4-b8148244c7e6
          name: affectionate-nightingale-3niy
          status:
            state: running
          droplet_id: '205545374'
          created_at: '2018-11-15T16:00:11Z'
          updated_at: '2018-11-15T16:00:11Z'
      maintenance_policy:
        start_time: '00:00'
        duration: 4h0m0s
        day: any
      auto_upgrade: false
      status:
        state: running
      created_at: '2018-11-15T16:00:11Z'
      updated_at: '2018-11-15T16:00:11Z'
      surge_upgrade: false
      registry_enabled: false
      ha: false

kubernetes_updated:
  value:
    kubernetes_cluster:
      id: bd5f5959-5e1e-4205-a714-a914373942af
      name: prod-cluster-01
      region: nyc1
      version: 1.18.6-do.0
      cluster_subnet: 10.244.0.0/16
      service_subnet: 10.245.0.0/16
      vpc_uuid: c33931f2-a26a-4e61-b85c-4e95a2ec431b
      ipv4: 68.183.121.157
      endpoint: https://bd5f5959-5e1e-4205-a714-a914373942af.k8s.ondigitalocean.com
      tags:
      - production
      - web-team
      - k8s
      - k8s:bd5f5959-5e1e-4205-a714-a914373942af
      node_pools:
      - id: cdda885e-7663-40c8-bc74-3a036c66545d
        name: frontend-pool
        size: s-1vcpu-2gb
        count: 3
        tags:
        - production
        - web-team
        - k8s
        - k8s:bd5f5959-5e1e-4205-a714-a914373942af
        - k8s:worker
        labels: null
        taints: []
        auto_scale: false
        min_nodes: 0
        max_nodes: 0
        nodes:
        - id: 478247f8-b1bb-4f7a-8db9-2a5f8d4b8f8f
          name: adoring-newton-3niq
          status:
            state: running
          droplet_id: '205545370'
          created_at: '2018-11-15T16:00:11Z'
          updated_at: '2018-11-15T16:00:11Z'
        - id: ad12e744-c2a9-473d-8aa9-be5680500eb1
          name: adoring-newton-3nim
          status:
            state: running
          droplet_id: '205545371'
          created_at: '2018-11-15T16:00:11Z'
          updated_at: '2018-11-15T16:00:11Z'
        - id: e46e8d07-f58f-4ff1-9737-97246364400e
          name: adoring-newton-3ni7
          status:
            state: running
          droplet_id: '205545372'
          created_at: '2018-11-15T16:00:11Z'
          updated_at: '2018-11-15T16:00:11Z'
      - id: f49f4379-7e7f-4af5-aeb6-0354bd840778
        name: backend-pool
        size: g-4vcpu-16gb
        count: 2
        tags:
        - production
        - web-team
        - k8s
        - k8s:bd5f5959-5e1e-4205-a714-a914373942af
        - k8s:worker
        labels:
          service: backend
          priority: high
        taints: []
        auto_scale: true
        min_nodes: 2
        max_nodes: 5
        nodes:
        - id: 3385619f-8ec3-42ba-bb23-8d21b8ba7518
          name: affectionate-nightingale-3nif
          status:
            state: running
          droplet_id: '205545373'
          created_at: '2018-11-15T16:00:11Z'
          updated_at: '2018-11-15T16:00:11Z'
        - id: 4b8f60ff-ba06-4523-a6a4-b8148244c7e6
          name: affectionate-nightingale-3niy
          status:
            state: running
          droplet_id: '205545374'
          created_at: '2018-11-15T16:00:11Z'
          updated_at: '2018-11-15T16:00:11Z'
      maintenance_policy:
        start_time: '00:00'
        duration: 4h0m0s
        day: any
      auto_upgrade: true
      status:
        state: running
      created_at: '2018-11-15T16:00:11Z'
      updated_at: '2018-11-15T16:00:11Z'
      surge_upgrade: true
      registry_enabled: false
      ha: false

kubernetes_clusters_create_basic_response:
  value:
    kubernetes_cluster:
      id: bd5f5959-5e1e-4205-a714-a914373942af
      name: prod-cluster-01
      region: nyc1
      version: 1.18.6-do.0
      cluster_subnet: 10.244.0.0/16
      service_subnet: 10.245.0.0/16
      vpc_uuid: c33931f2-a26a-4e61-b85c-4e95a2ec431b
      ipv4: ''
      endpoint: ''
      tags:
      - k8s
      - k8s:bd5f5959-5e1e-4205-a714-a914373942af
      node_pools:
      - id: cdda885e-7663-40c8-bc74-3a036c66545d
        name: worker-pool
        size: s-1vcpu-2gb
        count: 3
        tags:
        - k8s
        - k8s:bd5f5959-5e1e-4205-a714-a914373942af
        - k8s:worker
        labels: null
        taints: []
        auto_scale: false
        min_nodes: 0
        max_nodes: 0
        nodes:
        - id: 478247f8-b1bb-4f7a-8db9-2a5f8d4b8f8f
          name: ''
          status:
            state: provisioning
          droplet_id: ''
          created_at: '2018-11-15T16:00:11Z'
          updated_at: '2018-11-15T16:00:11Z'
        - id: ad12e744-c2a9-473d-8aa9-be5680500eb1
          name: ''
          status:
            state: provisioning
          droplet_id: ''
          created_at: '2018-11-15T16:00:11Z'
          updated_at: '2018-11-15T16:00:11Z'
        - id: e46e8d07-f58f-4ff1-9737-97246364400e
          name: ''
          status:
            state: provisioning
          droplet_id: ''
          created_at: '2018-11-15T16:00:11Z'
          updated_at: '2018-11-15T16:00:11Z'
      maintenance_policy:
        start_time: '00:00'
        duration: 4h0m0s
        day: any
      auto_upgrade: false
      status:
        state: provisioning
        message: provisioning
      created_at: '2018-11-15T16:00:11Z'
      updated_at: '2018-11-15T16:00:11Z'
      surge_upgrade: false
      registry_enabled: false
      ha: false

kubernetes_clusters_multi_pool_response:
  value:
    kubernetes_clusters:
      id: bd5f5959-5e1e-4205-a714-a914373942af
      name: prod-cluster-01
      region: nyc1
      version: 1.18.6-do.0
      cluster_subnet: 10.244.0.0/16
      service_subnet: 10.245.0.0/16
      vpc_uuid: c33931f2-a26a-4e61-b85c-4e95a2ec431b
      ipv4: ''
      endpoint: ''
      tags:
      - production
      - web-team
      - k8s
      - k8s:bd5f5959-5e1e-4205-a714-a914373942af
      node_pools:
      - id: cdda885e-7663-40c8-bc74-3a036c66545d
        name: frontend-pool
        size: s-1vcpu-2gb
        count: 3
        tags:
        - production
        - web-team
        - frontend
        - k8s
        - k8s:bd5f5959-5e1e-4205-a714-a914373942af
        - k8s:worker
        labels: null
        taints: []
        auto_scale: false
        min_nodes: 0
        max_nodes: 0
        nodes:
        - id: 478247f8-b1bb-4f7a-8db9-2a5f8d4b8f8f
          name: ''
          status:
            state: provisioning
          droplet_id: ''
          created_at: '2018-11-15T16:00:11Z'
          updated_at: '2018-11-15T16:00:11Z'
        - id: ad12e744-c2a9-473d-8aa9-be5680500eb1
          name: ''
          status:
            state: provisioning
          droplet_id: ''
          created_at: '2018-11-15T16:00:11Z'
          updated_at: '2018-11-15T16:00:11Z'
        - id: e46e8d07-f58f-4ff1-9737-97246364400e
          name: ''
          status:
            state: provisioning
          droplet_id: ''
          created_at: '2018-11-15T16:00:11Z'
          updated_at: '2018-11-15T16:00:11Z'
      - id: f49f4379-7e7f-4af5-aeb6-0354bd840778
        name: backend-pool
        size: g-4vcpu-16gb
        count: 2
        tags:
        - production
        - web-team
        - k8s
        - k8s:bd5f5959-5e1e-4205-a714-a914373942af
        - k8s:worker
        labels:
          service: backend
          priority: high
        taints: []
        auto_scale: true
        min_nodes: 2
        max_nodes: 5
        nodes:
        - id: 3385619f-8ec3-42ba-bb23-8d21b8ba7518
          name: ''
          status:
            state: provisioning
          droplet_id: ''
          created_at: '2018-11-15T16:00:11Z'
          updated_at: '2018-11-15T16:00:11Z'
        - id: 4b8f60ff-ba06-4523-a6a4-b8148244c7e6
          name: ''
          status:
            state: provisioning
          droplet_id: ''
          created_at: '2018-11-15T16:00:11Z'
          updated_at: '2018-11-15T16:00:11Z'
      maintenance_policy:
        start_time: '12:00'
        duration: 4h0m0s
        day: any
      auto_upgrade: false
      status:
        state: provisioning
        message: provisioning
      created_at: '2018-11-15T16:00:11Z'
      updated_at: '2018-11-15T16:00:11Z'
      surge_upgrade: false
      registry_enabled: false
      ha: false

kubernetes_options:
  value:
    options:
      regions:
        - name: New York 1
          slug: nyc1
        - name: Singapore 1
          slug: sgp1
        - name: London 1
          slug: lon1
        - name: New York 3
          slug: nyc3
        - name: Amsterdam 3
          slug: ams3
        - name: Frankfurt 1
          slug: fra1
        - name: Toronto 1
          slug: tor1
        - name: San Francisco 2
          slug: sfo2
        - name: Bangalore 1
          slug: blr1
        - name: San Francisco 3
          slug: sfo3
      versions:
        - slug: 1.18.8-do.0
          kubernetes_version: 1.18.8
          supported_features:
            - cluster-autoscaler
            - docr-integration
            - token-authentication
        - slug: 1.17.11-do.0
          kubernetes_version: 1.17.11
          supported_features:
            - cluster-autoscaler
            - docr-integration
            - token-authentication
        - slug: 1.16.14-do.0
          kubernetes_version: 1.16.14
          supported_features:
            - cluster-autoscaler
            - docr-integration
            - token-authentication
      sizes:
        - name: s-1vcpu-2gb
          slug: s-1vcpu-2gb
        - name: s-2vcpu-2gb
          slug: s-2vcpu-2gb
        - name: s-1vcpu-3gb
          slug: s-1vcpu-3gb
        - name: s-2vcpu-4gb
          slug: s-2vcpu-4gb
        - name: s-4vcpu-8gb
          slug: s-4vcpu-8gb
        - name: c-2-4GiB
          slug: c-2
        - name: g-2vcpu-8gb
          slug: g-2vcpu-8gb
        - name: gd-2vcpu-8gb
          slug: gd-2vcpu-8gb
        - name: s-8vcpu-16gb
          slug: s-8vcpu-16gb
        - name: s-6vcpu-16gb
          slug: s-6vcpu-16gb
        - name: c-4-8GiB
          slug: c-4
        - name: m-2vcpu-16gb
          slug: m-2vcpu-16gb
        - name: m3-2vcpu-16gb
          slug: m3-2vcpu-16gb
        - name: g-4vcpu-16gb
          slug: g-4vcpu-16gb
        - name: gd-4vcpu-16gb
          slug: gd-4vcpu-16gb
        - name: m6-2vcpu-16gb
          slug: m6-2vcpu-16gb
        - name: s-8vcpu-32gb
          slug: s-8vcpu-32gb
        - name: c-8-16GiB
          slug: c-8
        - name: m-4vcpu-32gb
          slug: m-4vcpu-32gb
        - name: m3-4vcpu-32gb
          slug: m3-4vcpu-32gb
        - name: g-8vcpu-32gb
          slug: g-8vcpu-32gb
        - name: s-12vcpu-48gb
          slug: s-12vcpu-48gb
        - name: gd-8vcpu-32gb
          slug: gd-8vcpu-32gb
        - name: m6-4vcpu-32gb
          slug: m6-4vcpu-32gb
        - name: s-16vcpu-64gb
          slug: s-16vcpu-64gb
        - name: c-16
          slug: c-16
        - name: m-8vcpu-64gb
          slug: m-8vcpu-64gb
        - name: m3-8vcpu-64gb
          slug: m3-8vcpu-64gb
        - name: g-16vcpu-64gb
          slug: g-16vcpu-64gb
        - name: s-20vcpu-96gb
          slug: s-20vcpu-96gb
        - name: gd-16vcpu-64gb
          slug: gd-16vcpu-64gb
        - name: m6-8vcpu-64gb
          slug: m6-8vcpu-64gb
        - name: s-24vcpu-128gb
          slug: s-24vcpu-128gb
        - name: c-32-64GiB
          slug: c-32
        - name: m-16vcpu-128gb
          slug: m-16vcpu-128gb
        - name: m3-16vcpu-128gb
          slug: m3-16vcpu-128gb
        - name: g-32vcpu-128gb
          slug: g-32vcpu-128gb
        - name: s-32vcpu-192gb
          slug: s-32vcpu-192gb
        - name: gd-32vcpu-128gb
          slug: gd-32vcpu-128gb
        - name: m-24vcpu-192gb
          slug: m-24vcpu-192gb
        - name: m6-16vcpu-128gb
          slug: m6-16vcpu-128gb
        - name: g-40vcpu-160gb
          slug: g-40vcpu-160gb
        - name: gd-40vcpu-160gb
          slug: gd-40vcpu-160gb
        - name: m3-24vcpu-192gb
          slug: m3-24vcpu-192gb
        - name: m-32vcpu-256gb
          slug: m-32vcpu-256gb
        - name: m6-24vcpu-192gb
          slug: m6-24vcpu-192gb
        - name: m3-32vcpu-256gb
          slug: m3-32vcpu-256gb
        - name: m6-32vcpu-256gb
          slug: m6-32vcpu-256gb
