name: "openapi-fetch: Feature request"
description: Propose new functionality or a breaking change
labels:
  - openapi-fetch
  - enhancement
projects:
  - openapi-ts/3
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Brief description of the problem you’re trying to solve, and why this could be useful.
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposal
      description: Describe the proposed syntax change. Please reference any prior art or similar examples.
    validations:
      required: true
  - type: checkboxes
    id: extra
    attributes:
      label: Extra
      options:
        - label: I’m willing to open a PR (see [CONTRIBUTING.md](https://github.com/openapi-ts/openapi-typescript/blob/main/packages/openapi-fetch/CONTRIBUTING.md))
