description: |
  The response will be a JSON object with a key called `kubernetes_cluster`. The
  value of this will be an object containing the standard attributes of a
  Kubernetes cluster.

headers:
  ratelimit-limit:
    $ref: '../../../shared/headers.yml#/ratelimit-limit'
  ratelimit-remaining:
    $ref: '../../../shared/headers.yml#/ratelimit-remaining'
  ratelimit-reset:
    $ref: '../../../shared/headers.yml#/ratelimit-reset'

content:
  application/json:
    schema:
      properties:
        kubernetes_cluster:
          $ref: '../models/cluster.yml'
    examples:
      Single Kubernetes Cluster:
        $ref: 'examples.yml#/kubernetes_single'